# Generated by Django 6.0.3 on 2026-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="competencias",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="grau",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="conteudos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
    ]
