# Generated by Django 6.0.3 on 2026-05-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_licenciatura_competencias_licenciatura_grau_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="opiniao",
            field=models.TextField(blank=True, help_text="O que gostei ou não"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(help_text="O que faz e o que permite"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="nivel_interesse",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tecnologias",
                to="portfolio.tipotecnologia",
            ),
        ),
    ]
