# Generated by Django 6.0.3 on 2026-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_tipotecnologia_tecnologia_opiniao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnologia",
            name="link_oficial",
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="ink_oficial",
            field=models.URLField(blank=True),
        ),
    ]
