# Generated by Django 6.0.3 on 2026-05-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artigo",
            name="likes",
        ),
        migrations.AlterField(
            model_name="comentario",
            name="autor",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.IntegerField()),
                ("ip", models.GenericIPAddressField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="artigos.artigo",
                    ),
                ),
            ],
            options={
                "unique_together": {("artigo", "ip")},
            },
        ),
    ]
